export const industriaConfig = {
  construccion: {
    activo: "Maquinaria",
    activoPlural: "Maquinaria",
    activoIcon: "construction",
    activoCampos: {
      nombre: "Nombre del equipo",
      tipo: "Tipo",
      marca: "Marca/Modelo",
      año: "Año",
      ubicacion: "Ubicación",
      estado: "Estado",
    },
    activoEjemplos: {
      nombre: "Excavadora CAT 320",
      tipo: "Excavadora",
      marca: "Caterpillar 320",
    },
    inventario: "Refacciones",
    inventarioIcon: "inventory_2",
    tieneOperadores: false,
  },
  transporte: {
    activo: "Flotilla",
    activoPlural: "Vehículos",
    activoIcon: "local_shipping",
    activoCampos: {
      nombre: "Nombre del vehículo",
      tipo: "Tipo",
      marca: "Marca/Modelo",
      año: "Año",
      ubicacion: "Base/Ruta",
      estado: "Estado",
    },
    activoEjemplos: {
      nombre: "Camión Kenworth T680",
      tipo: "Camión",
      marca: "Kenworth T680",
    },
    inventario: "Refacciones",
    inventarioIcon: "build",
    tieneOperadores: true,
  },
  movilidad: {
    activo: "Vehículos",
    activoPlural: "Vehículos",
    activoIcon: "directions_car",
    activoCampos: {
      nombre: "Nombre del vehículo",
      tipo: "Tipo",
      marca: "Marca/Modelo",
      año: "Año",
      ubicacion: "Zona",
      estado: "Estado",
    },
    activoEjemplos: {
      nombre: "Sedan Toyota Corolla",
      tipo: "Sedan",
      marca: "Toyota Corolla",
    },
    inventario: "Refacciones",
    inventarioIcon: "build",
    tieneOperadores: true,
  },
  medico: {
    activo: "Equipos",
    activoPlural: "Equipos Médicos",
    activoIcon: "medical_services",
    activoCampos: {
      nombre: "Nombre del equipo",
      tipo: "Tipo",
      marca: "Marca/Modelo",
      año: "Año",
      ubicacion: "Área/Piso",
      estado: "Estado",
    },
    activoEjemplos: {
      nombre: "Resonancia MRI 3T",
      tipo: "Resonancia",
      marca: "Siemens Magnetom",
    },
    inventario: "Insumos",
    inventarioIcon: "medical_information",
    tieneOperadores: false,
  },
  inmobiliaria: {
    activo: "Propiedades",
    activoPlural: "Propiedades",
    activoIcon: "apartment",
    activoCampos: {
      nombre: "Nombre de la propiedad",
      tipo: "Tipo",
      marca: "Dirección",
      año: "Año construcción",
      ubicacion: "Colonia/Ciudad",
      estado: "Estado",
    },
    activoEjemplos: {
      nombre: "Local Comercial Plaza Norte",
      tipo: "Local Comercial",
      marca: "Av. Principal 123",
    },
    inventario: "Mantenimiento",
    inventarioIcon: "home_repair_service",
    tieneOperadores: false,
  },
};